---
# tasks file for /Users/carlosfrias/apigee-workspace/opdk-workspace/apigee-opdk-setup-analytics-group-add

- name: Add analytics group
  uri:
    user: '{{ opdk_user_email }}'
    password: '{{ opdk_user_pass }}'
    method: POST
    url: http://{{ local_mgmt_ip }}:8080/v1/analytics/groups/{{ new_ax_group }}
    body_format: json

- name: Add analytics consumer group
  uri:
    user: '{{ opdk_user_email }}'
    password: '{{ opdk_user_pass }}'
    method: POST
    url: http://{{ local_mgmt_ip }}:8080/v1/analytics/groups/{{ new_ax_group }}/consumer-groups/?name={{ new_consumer_group }}
    body_format: json

- name: Add analytics group consumer-type attribute
  uri:
    user: '{{ opdk_user_email }}'
    password: '{{ opdk_user_pass }}'
    method: POST
    url: http://{{ local_mgmt_ip }}:8080/v1/analytics/groups/{{ new_ax_group }}/properties?propName=consumer-type&propValue=ax
    body_format: json


- name: Add analytics group region attribute
  uri:
    user: '{{ opdk_user_email }}'
    password: '{{ opdk_user_pass }}'
    method: POST
    url: http://{{ local_mgmt_ip }}:8080/v1/analytics/groups/{{ new_ax_group }}/properties?propName=region&propValue={{ region }}
    body_format: json

